# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Greg Potter
tagline:          'Full Stack Java Developer'
description:      'Full Stack Java Developer'
url:              https://gdpotter.com

author:
  name:           'Greg Potter'

paginate:         5

# Custom vars
version:          1.0.0
github_username:      gdpotter
linkedin_username:    gdpotter

github:
  repo:           https://github.com/gdpotter/gdpotter.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-crosspost-to-medium
