# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Greg Potter
tagline:          'Full Stack Java Developer'
description:      'Full Stack Java Developer' #'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Greg Potter'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0
github_username:      gdpotter
linkedin_username:    gdpotter
facebook_username:    gdpotter

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]
